update: (workflow) Try fix release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,57 +1,79 @@
-name: Compile and Release
+name: Compile and Release for Server
 
 on:
-  push:
-    branches:
-      - master
-
+    push:
+        branches:
+            - master
+        paths:
+            - "package.json"
+            - ".github/**"
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        version:
-          [
-            "linux-x64",
-            "linux-arm64",
-            "windows-x64",
-            "darwin-x64",
-            "darwin-arm64",
-          ]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2.0.1
+    build:
+        runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                version: ["linux-x64", "linux-arm64", "windows-x64", "darwin-x64", "darwin-arm64"]
+        steps:
+            - uses: actions/checkout@v4
+            - uses: oven-sh/setup-bun@v2.0.1
+            - name: Install UPX
+              uses: crazy-max/ghaction-upx@v3
+              with:
+                  install-only: true
+            - name: Dependencies version
+              run: |
+                  echo "=== System Info ==="
+                  uname -a && cat /etc/os-release
+                  lscpu && cat /proc/meminfo | head -n 5
+                  nproc && cat /proc/cpuinfo
 
-      - name: Extract version number
-        id: get_version
-        run: echo "::set-output name=VERSION::$(jq -r .version < package.json)"
+                  echo -e "\n=== Dependencies Version ==="
+                  upx --version
+                  bun --version
 
-      - name: Install Dependencies
-        run: bun install
+            - name: Extract version number
+              id: get_version
+              run: echo "::set-output name=VERSION::$(jq -r .version < package.json)"
 
-      - name: Compile Code
-        run: |
-          mkdir out
-          bun build --compile --target=bun-${{ matrix.version }} ./index.ts --outfile out/telegrampraser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}
-          cp ${GITHUB_WORKSPACE}/README.md ./out/README.md
-          cp ${GITHUB_WORKSPACE}/LICENSE ./out/LICENSE
-          cp .env.example ./out/.env.example
-          cp -r ${GITHUB_WORKSPACE}/database ./out/database
+            - name: Install Dependencies
+              run: |
+                  cd server/ || { echo "Directory not found"; exit 1; }
+                  bun install
 
-      - name: Zip Output Directory
-        run: |
-          cd out
-          zip -r ../telegrampraser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}.zip .
+            - name: Compile Code
+              run: |
+                  mkdir out
+                  bun build --compile --target=bun-${{ matrix.version }} ./index.ts --outfile out/telegram-parser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}
+                  cp ${GITHUB_WORKSPACE}/README.md ./out/README.md
+                  cp ${GITHUB_WORKSPACE}/LICENSE ./out/LICENSE
+                  cp .env.example ./out/.env.example
+                  cp -r ${GITHUB_WORKSPACE}/database ./out/database
+                  cp -r ${GITHUB_WORKSPACE}/logs ./out/logs
+                  cp -r ${GITHUB_WORKSPACE}/scripts ./out/scripts
 
-      - name: Create GitHub Release
-        uses: ncipollo/release-action@v1
-        with:
-          artifacts: "telegrampraser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}.zip"
-          token: ${{ secrets.GITHUB_TOKEN }}
-          tag: v${{ steps.get_version.outputs.VERSION }}
-          name: Release ${{ steps.get_version.outputs.VERSION }}
-          body: "Release of version ${{ steps.get_version.outputs.VERSION }}"
-          draft: false
-          prerelease: false
-          allowUpdates: true
-          generateReleaseNotes: true
+            - name: Upx Compress
+              run: |
+                  cd out
+                  upx --best --lzma --ultra-brute telegram-parser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}
+
+            - name: Package Output
+              run: |
+                  if [[ "${{ matrix.version }}" == linux* ]]; then
+                    tar -cJf ../telegram-parser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}.tar.xz *
+                  else
+                    zip -r ../telegram-parser-${{ matrix.version }}_v${{ steps.get_version.outputs.VERSION }}.zip *
+                  fi
+
+            - name: Create GitHub Release
+              uses: ncipollo/release-action@v1
+              with:
+                  artifacts: |
+                      ${{ startsWith(matrix.version, 'linux') && format('telegram-parser-{0}_v{1}.tar.xz', matrix.version, steps.get_version.outputs.VERSION) || format('telegram-parser-{0}_v{1}.zip', matrix.version, steps.get_version.outputs.VERSION) }}
+                  token: ${{ secrets.GITHUB_TOKEN }}
+                  tag: v${{ steps.get_version.outputs.VERSION }}
+                  name: Release ${{ steps.get_version.outputs.VERSION }}
+                  body: "Release of version ${{ steps.get_version.outputs.VERSION }}"
+                  draft: false
+                  prerelease: false
+                  allowUpdates: true
+                  generateReleaseNotes: true
